
import type { Spot } from '@/lib/types';

// This data is intentionally different from data.ts to avoid overwriting user data on initial seed.
// This is used by the TempSeedButton to add more spots to the database.
export const spots: Spot[] = [
    {
        id: 'new-spot-1',
        title: '[NEW] The Colosseum',
        description: 'An iconic ancient amphitheater in the center of Rome, Italy, known for its gladiatorial contests and public spectacles.',
        category: 'architecture',
        location: { lat: 41.8902, lng: 12.4922, heading: 270, pitch: 0, fov: 90 },
        jurisdiction: { city: 'Rome', country: 'Italy' },
        authorId: 'user-1',
        createdAt: '2024-06-10T09:00:00Z',
    },
    {
        id: 'new-spot-2',
        title: '[NEW] Hobbiton Movie Set',
        description: 'Step into the world of Middle-earth. The charming Hobbit holes and the Green Dragon Inn are a must-see for any fan.',
        category: 'cool',
        location: { lat: -37.8573, lng: 175.6796, heading: 120, pitch: 5, fov: 100 },
        jurisdiction: { city: 'Matamata', country: 'New Zealand' },
        authorId: 'user-3',
        createdAt: '2024-01-20T11:00:00Z',
    },
    {
        id: 'new-spot-3',
        title: '[NEW] The Great Pyramid of Giza',
        description: 'The last remaining wonder of the ancient world. Its sheer size and age are humbling.',
        category: 'interesting',
        location: { lat: 29.9792, lng: 31.1342, heading: 45, pitch: 0, fov: 80 },
        jurisdiction: { city: 'Giza', country: 'Egypt' },
        authorId: 'user-1',
        createdAt: '2023-09-10T08:20:00Z',
    },
    {
        id: 'new-spot-4',
        title: '[NEW] The Door to Hell',
        description: 'A giant natural gas crater in Turkmenistan that has been burning continuously for over 50 years. A truly hellish landscape.',
        category: 'creepy',
        location: { lat: 40.2522, lng: 58.4394, heading: 0, pitch: 10, fov: 100 },
        jurisdiction: { city: 'Darvaza', country: 'Turkmenistan' },
        authorId: 'user-2',
        createdAt: '2023-08-01T22:00:00Z',
    },
    {
        id: 'new-spot-5',
        title: '[NEW] Salar de Uyuni',
        description: 'The world\'s largest salt flat creates a mesmerizing mirror effect during the rainy season. It feels like walking on the sky.',
        category: 'beautiful',
        location: { lat: -20.2288, lng: -67.4891, heading: 180, pitch: 0, fov: 110 },
        jurisdiction: { country: 'Bolivia' },
        authorId: 'user-3',
        createdAt: '2024-04-01T13:00:00Z',
    },
    {
        id: 'new-spot-6',
        title: '[NEW] The Island of the Dolls',
        description: 'A creepy island in Mexico filled with hundreds of decaying dolls hanging from trees, said to be haunted by the spirit of a young girl.',
        category: 'creepy',
        location: { lat: 19.2907, lng: -99.0982, heading: 30, pitch: 5, fov: 90 },
        jurisdiction: { city: 'Xochimilco', country: 'Mexico' },
        authorId: 'user-2',
        createdAt: '2023-10-31T23:59:00Z',
    },
    {
        id: 'new-spot-7',
        title: '[NEW] Fly Geyser',
        description: 'A bizarre, multicolored geyser in the Nevada desert that was accidentally created by well drilling. It looks like it belongs on another planet.',
        category: 'strange',
        location: { lat: 40.8587, lng: -119.3331, heading: 240, pitch: 15, fov: 100 },
        jurisdiction: { state: 'NV', country: 'USA' },
        authorId: 'user-3',
        createdAt: '2024-05-10T16:20:00Z',
    },
    {
        id: 'new-spot-8',
        title: '[NEW] Underwater Sculpture Park',
        description: 'A collection of hauntingly beautiful sculptures submerged in the clear waters off the coast of Grenada.',
        category: 'art',
        location: { lat: 12.0835, lng: -61.7661, heading: 150, pitch: 20, fov: 90 },
        jurisdiction: { country: 'Grenada' },
        authorId: 'user-1',
        createdAt: '2024-03-01T11:30:00Z',
    },
    {
        id: 'new-spot-9',
        title: '[NEW] Cat Island (Tashirojima)',
        description: 'Tashirojima in Japan is an island where cats outnumber humans, roaming freely and bringing good luck.',
        category: 'people',
        location: { lat: 38.3186, lng: 141.4172, heading: 90, pitch: 0, fov: 100 },
        jurisdiction: { country: 'Japan' },
        authorId: 'user-2',
        createdAt: '2023-09-22T13:10:00Z',
    },
    {
        id: 'new-spot-10',
        title: '[NEW] Abandoned Soviet Space Shuttles',
        description: 'Two abandoned Buran-class space shuttles sit decaying in a massive hangar at the Baikonur Cosmodrome.',
        category: 'abandoned',
        location: { lat: 45.9205, lng: 63.3444, heading: 270, pitch: 10, fov: 110 },
        jurisdiction: { country: 'Kazakhstan' },
        authorId: 'user-1',
        createdAt: '2023-07-18T05:00:00Z',
    }
];

    