// This file is automatically generated. Do not modify it.
'use client';
import { ReactNode, useEffect, useState } from 'react';
import { FirebaseProvider } from './provider';

// This provider is used to ensure that Firebase is only initialized on the client side.
export function FirebaseClientProvider({ children }: { children: ReactNode }) {
  const [isClient, setIsClient] = useState(false);

  useEffect(() => {
    setIsClient(true);
  }, []);

  if (!isClient) {
    // Render nothing on the server
    return null;
  }

  return <FirebaseProvider>{children}</FirebaseProvider>;
}
