// This file is automatically generated. Do not modify it.
export type SecurityRuleContext = {
  path: string;
  operation: 'get' | 'list' | 'create' | 'update' | 'delete';
  requestResourceData?: any;
};

export class FirestorePermissionError extends Error {
  constructor(public context: SecurityRuleContext) {
    const { path, operation, requestResourceData } = context;

    let message = `FirestoreError: Missing or insufficient permissions: 
The following request was denied by Firestore Security Rules:
{
  "auth": {
    "uid": "...",
    "token": {
      "name": "...",
      "picture": "...",
      "email": "...",
      "email_verified": "...",
      "phone_number": "...",
      "firebase": {
        "identities": {
          "google.com": [],
          "facebook.com": [],
          "github.com": [],
          "microsoft.com": [],
          "password": [],
          "phone": [],
          "saml.example": [],
          "twitter.com": [],
          "yahoo.com": []
        },
        "sign_in_provider": "..."
      }
    }
  },
  "method": "${operation}",
  "path": "/databases/(default)/documents/${path}"`;

    if (requestResourceData) {
      message += `,
  "request": {
    "resource": {
      "data": ${JSON.stringify(requestResourceData, null, 2)}
    }
  }`;
    }

    message += `
}`;
    super(message);
    this.name = 'FirestorePermissionError';
  }
}
